# Generated by Django 5.1.2 on 2024-11-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0003_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Cancelled by FindMe', 'Cancelled by FindMe')], default='Upcoming', max_length=50),
        ),
    ]
